#
# (C) Copyright 2007-2008 Michal Simek
#
# Michal SIMEK <monstr@monstr.eu>
#
# CAUTION: This file is automatically generated by libgen.
# Version: Xilinx EDK 14.7 EDK_P.20131013
# Generate by U-BOOT v4.00.c
# Project description at http://www.monstr.eu/uboot/
#

CONFIG_SYS_TEXT_BASE = 0x4fc00000

PLATFORM_CPPFLAGS += -mxl-pattern-compare
PLATFORM_CPPFLAGS += -mxl-barrel-shift
PLATFORM_CPPFLAGS += -mno-xl-soft-div
PLATFORM_CPPFLAGS += -mxl-multiply-high
PLATFORM_CPPFLAGS += -mno-xl-soft-mul
PLATFORM_CPPFLAGS += -mcpu=v8.50.c

