/*
 * (C) Copyright 2007-2008 Michal Simek
 *
 * Michal SIMEK <monstr@monstr.eu>
 *
 * CAUTION: This file is automatically generated by libgen.
 * Version: Xilinx EDK 14.7 EDK_P.20131013
 * Generate by U-BOOT v4.00.c
 * Project description at http://www.monstr.eu/uboot/
 */

#define XILINX_BOARD_NAME	FREEPCX_MM

/* Microblaze is microblaze_0 */
#define XILINX_USE_MSR_INSTR	1
#define XILINX_PVR		2
#define XILINX_FSL_NUMBER	0
#define XILINX_USE_ICACHE	1
#define XILINX_USE_DCACHE	1
#define XILINX_DCACHE_BYTE_SIZE	32768

/* Interrupt controller is xps_intc_0 */
#define XILINX_INTC_BASEADDR		0x81800000
#define XILINX_INTC_NUM_INTR_INPUTS	18

/* Timer pheriphery is xps_timer_0 */
#define XILINX_TIMER_BASEADDR	0x83c00000
#define XILINX_TIMER_IRQ	0

/* System Timer Clock Frequency */
#define XILINX_CLOCK_FREQ	62500000

/* Uart console is rs232_uart_1 */
#define XILINX_UARTLITE_BASEADDR	0x84000000
#define XILINX_UARTLITE_BAUDRATE	115200

/* IIC doesn't exist */

/* SPI controller */
#define XILINX_SPI_BASEADDR	0x83400000

/* GPIO is leds_8bit*/
#define XILINX_GPIO_BASEADDR	0x81420000

/* SDIO doesn't exist */

/* Main Memory is ddr2_sdram */
#define XILINX_RAM_START	0x48000000
#define XILINX_RAM_SIZE		0x08000000

/* Flash Memory is flash */
#define XILINX_FLASH_START	0x82000000
#define XILINX_FLASH_SIZE	0x01000000

/* Sysace doesn't exist */

/* Ethernet controller is soft_temac */
#define XILINX_LLTEMAC_BASEADDR			0x87000000
#define XILINX_LLTEMAC_SDMA_CTRL_BASEADDR	0x84600080
